"use client";

import { Roboto } from 'next/font/google'
import './globals.css'

const roboto = Roboto({
    weight: ['300', '400', '500', '700'],
    subsets: ['latin'],
    variable: '--font-roboto',
});

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <title>Fazilabs Digital Service</title>
            <meta name="description" content="Fazilabs Digital Services - Transforming ideas into stunning websites and mobile apps." />
            <meta name="keywords" content="Fazilabs, Digital Services, Web Development, Mobile Apps, SEO, WordPress, React Native" />
            <meta name="author" content="Fazilabs" />
        </head>
        <body className={`${roboto.variable} antialiased`}>
            <style jsx global>{`
              body {
                font-family: 'Roboto', sans-serif;
                background-color: #f9fafb;
                color: #1f2937;
                margin: 0;
                padding: 0;
                box-sizing: border-box;
              }
              a {
                text-decoration: none;
                color: inherit;
              }
              button {
                cursor: pointer;
              }
              * {
                box-sizing: inherit;
              }
            `}</style>
            {children}
        </body>
        </html>
    );
}