"use client";

import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <title>Fazilabs Digital Service</title>
            <meta name="description" content="Fazilabs Digital Services - Transforming ideas into stunning websites and mobile apps." />
            <meta name="keywords" content="Fazilabs, Digital Services, Web Development, Mobile Apps, SEO, WordPress, React Native" />
            <meta name="author" content="Fazilabs" />
        </head>
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
            <style jsx global>{`
              body {
                font-family: 'Inter', sans-serif;
                background-color: #f9fafb;
                color: #1f2937;
                margin: 0;
                padding: 0;
                box-sizing: border-box;
              }
              a {
                text-decoration: none;
                color: inherit;
              }
              button {
                cursor: pointer;
              }
              * {
                box-sizing: inherit;
              }
            `}</style>
            {children}
        </body>
        </html>
    );
}